---

- name: Configure SELinux to allow httpd to connect to remote databses
  seboolean: name=httpd_can_network_connect state=true persistent=yes

- name: Download application
  get_url:
    url: "{{ app_zip_url }}"
    dest: "/tmp/application-{{ app_version }}.zip"
  register: download

- name: Extract application
  unarchive:
    src: "/tmp/application-{{ app_version }}.zip"
    dest: "/tmp"
    remote_src: yes
  when: download|changed

- name: Remove old application
  file:
    path: /var/www/html
    state: absent

- name: Add new application
  shell: "cp -r /tmp/Simple_AJAX_Todo_List-{{ app_version }}/ /var/www/html"

- name: update database connection
  template:
    src: connect.php.j2
    dest: "/var/www/html/includes/connect.php"
